
columns:

  Item_Identifier : object
  Item_Weight      : float64
  Item_Fat_Content  : object
  Item_Visibility : float64
  Item_Type         : object
  Item_MRP         : float64
  Outlet_Identifier : object
  Outlet_Establishment_Year : int64
  Outlet_Size : object
  Outlet_Location_Type : object
  Outlet_Type : object
  Item_Outlet_Sales : float64

numerical_columns:
- Item_Weight
- Item_Visibility
- Item_MRP
- Outlet_Establishment_Year
- Item_Outlet_Sales

categorical_columns:
- Item_Identifier
- Item_Fat_Content
- Item_Type
- Outlet_Identifier
- Outlet_Size
- Outlet_Location_Type
- Outlet_Type

column_to_be_dropped : Item_Identifier

target_column: Item_Outlet_Sales

domain_value:
  Item_Fat_Content:
  - <Low Fat
  - <Regular
  - <low fat
  - <LF
  - <reg
  Item_Type:
  - <Dairy
  - <Soft Drinks
  - <Meat
  - <Fruits and Vegetables
  - <Household
  - <Baking Goods
  - <Snack Foods
  - <Frozen Foods
  - <Breakfast
  - <Health and Hygiene
  - <Hard Drinks
  - <Canned
  - <Breads
  - <Starchy Foods
  - <Others
  - <Seafood
  Outlet_Identifier:
  - <OUT049
  - <OUT018
  - <OUT010
  - <OUT013
  - <OUT027
  - <OUT045
  - <OUT017
  - <OUT046
  - <OUT035
  - <OUT019
  Outlet_Size:
  - <Medium
  - <nan
  - <High
  - <Small
  Outlet_Location_Type:
  - <Tier 1
  - <Tier 3
  - <Tier 2
  Outlet_Type:
  - <Supermarket Type1
  - <Supermarket Type2
  - <Grocery Store
  - <Supermarket Type3
